# -*- coding: utf-8 -*-
"""ner-transformer-token-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152Ih0rxZ7VYAfuLjci6NZ89mB-0YMLtX
"""

!pip install -q datasets transformers evaluate seqeval accelerate

from datasets import load_dataset

# Load dataset
ds = load_dataset("lhoestq/conll2003")

# Inspect one sample
print(ds["train"][0])

label_names = [
    "O",
    "B-PER",
    "I-PER",
    "B-ORG",
    "I-ORG",
    "B-LOC",
    "I-LOC",
    "B-MISC",
    "I-MISC"
]

id2label = {i: label for i, label in enumerate(label_names)}
label2id = {label: i for i, label in enumerate(label_names)}

print(id2label)
print(label2id)

ds["train"][0]

from transformers import AutoTokenizer

model_nm = "distilbert-base-uncased"
tokz = AutoTokenizer.from_pretrained(model_nm)

def tokenize_and_align_labels(examples):
    tokenized_inputs = tokz(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True
    )

    labels = []

    for i, label in enumerate(examples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []

        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            else:
                label_ids.append(-100)

            previous_word_idx = word_idx

        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

tok_ds = ds.map(tokenize_and_align_labels, batched=True)
tok_ds

from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer=tokz)

!pip install -q evaluate seqeval
import evaluate
import numpy as np

seqeval = evaluate.load("seqeval")

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = []
    true_labels = []

    for prediction, label in zip(predictions, labels):
        current_preds = []
        current_labels = []

        for pred_id, label_id in zip(prediction, label):
            if label_id != -100:
                current_preds.append(label_names[pred_id])
                current_labels.append(label_names[label_id])

        true_predictions.append(current_preds)
        true_labels.append(current_labels)

    results = seqeval.compute(
        predictions=true_predictions,
        references=true_labels
    )

    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

from transformers import AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(
    model_nm,
    num_labels=len(label_names),
    id2label=id2label,
    label2id=label2id
)

from transformers import TrainingArguments, Trainer

args = TrainingArguments(
    output_dir="ner_model",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tok_ds["train"],
    eval_dataset=tok_ds["validation"],
    processing_class=tokz,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

ev=trainer.evaluate()
ev

from transformers import pipeline

ner_pipe = pipeline(
    "token-classification",
    model=model,
    tokenizer=tokz,
    aggregation_strategy="simple"
)

ner_pipe("Barack Obama was born in Hawaii and worked for Microsoft.")

trainer.save_model("ner_transformer_model")
tokz.save_pretrained("ner_transformer_model")

def show_entities(text):
    results = ner_pipe(text)

    print("Text:", text)
    print("-" * 80)

    for ent in results:
        word = ent["word"]
        label = ent["entity_group"]
        score = ent["score"]

        print(f"{word:25s} → {label:10s} | confidence: {score:.4f}")

texts = [
    "Elon Musk founded SpaceX in California.",
    "Google opened a new office in London.",
    "Cristiano Ronaldo played for Manchester United in England.",
    "Amazon was founded by Jeff Bezos in Seattle."
]

for text in texts:
    print("TEXT:", text)
    print(ner_pipe(text))
    print("-" * 80)